meta:
  version: 0.1.0
  name: my-redis-connector-sink-test-connector
  type: redis-sink
  topic: webinariiot
  consumer:
    max_bytes: 150000000
redis:
  prefix: webinariiot
  url:
    secret:
      name: "REDIS_URL"
  operation: "SET"
